- name: install python-httplib2 for uri module
  apt: name=python-httplib2
  
- name: check if there are packages designed for {{ ansible_distribution_release }}
  uri:
      url: "http://hwraid.le-vert.net/ubuntu/dists/{{ ansible_distribution_release }}"
      
  register: distribution_support
  failed_when: no

- name: set distribution
  set_fact:
      distr: "{{ hwraid_le_vert_net_latest_distr if distribution_support.status == 404 else ansible_distribution_release  }}"

- debug: msg="check status={{ distribution_support.status }} distr={{ distr }}"

- name: add key
  apt_key: url=http://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key

- name: add hwraid.le-vert.net repo
  apt_repository: repo='deb http://hwraid.le-vert.net/ubuntu {{ distr }} main' update_cache=yes
  
- name: install packages for 3Ware Eskalad 7000/8000/9000
  apt: name={{ item }}
  with_items:
      - 3ware-status
      - tw-cli
      - 3dm2
  when: "{{ hwraid_target == '3Ware' }}"

- name: install packages for Adaptec AACRaid
  apt: name={{ item }}
  with_items:
      - aacraid-status
      - adaptec-storage-manager-agent
      - adaptec-storage-manager-common
      - adaptec-storage-manager-gui
      - arcconf
      - hrconf
      - adaptec-universal-storage-snmpd
      - adaptec-universal-storage-mib
  when: "{{ hwraid_target == 'Adaptec' }}"

- name: install packages for HP/Compaq SmartArray
  apt: name={{ item }}
  with_items:
      - cciss-vol-status
      - hpacucli
  when: "{{ hwraid_target == 'SmartArray' }}"

- name: install packages for LSI MegaRAID / MegaRAID SAS
  apt: name={{ item }}
  with_items:
      - megaraid-status
      - megactl
  when: "{{ hwraid_target in ['MegaRAID','MegaRAID_SAS','MegaRAID_Dell'] }}"
  
- name: install packages for LSI MegaRAID
  apt: name={{ item }}
  with_items:
      - megamgr
  when: "{{ hwraid_target == 'MegaRAID' }}"
  
- name: install packages for LSI MegaRAID (Dell cards only)
  apt: name={{ item }}
  with_items:
      - dellmgr
  when: "{{ hwraid_target == 'MegaRAID_Dell' }}"

- name: install packages for LSI MegaRAID SAS
  apt: name={{ item }}
  with_items:
      - megaclisas-status
      - megacli
  when: "{{ hwraid_target == 'MegaRAID_SAS' }}"
  
- name: install packages for LSI MegaIDE
  apt: name={{ item }}
  with_items:
      - megaide-status
      - megaide-spyd
  when: "{{ hwraid_target == 'MegaIDE' }}"
  
- name: install packages for LSI FusionMPT
  apt: name={{ item }}
  with_items:
      - mpt-status
      - lsiutil
  when: "{{ hwraid_target == 'FusionMPT' }}"

- name: install packages for LSI FusionMPT SAS2
  apt: name={{ item }}
  with_items:
      - sas2ircu
      - sas2ircu-status
  when: "{{ hwraid_target == 'FusionMPT_SAS2' }}"
